# -*- coding: utf-8 -*-
"""Assignment3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17dK8nFLhZoR8_S_m4RizUZKiWcXHn64f
"""

import random as rd
sample_size=int(1e6)
#from the question
#the probability of hundred's digit will not be equal to 7 be pr_a
pr_a=8/9
#the probability of ten's digit will not be equal to 7 be pr_b
pr_b=9/10
#the probability of one's digit will not be equal to 7 be pr_c
pr_c=9/10
#the probability of a random 3-digit number will not contain digit 7 be pr_abc
pr_abc=pr_a*pr_b*pr_c

count_A=0
#count_A is the no.of 3 digit integers contain digit 7

#simulating
for i in range(sample_size):
   temp = rd.randint(100,999)
   if(temp%10==7 or int(temp/10)%10==7 or int(temp/100) ==7):
    count_A+=1
#pr_A is the probability of a 3 digit random number contain digit 7
pr_A=count_A/sample_size
#theory vs simulation
print("Theoritical and simulated values of probability of a random 3-digit number will not contain digit 7 are",pr_abc, "and",1-pr_A, "respectively")